### ISSUE TITLE
Using on CI

### ISSUE THREAD

**Issue by Ch4s3** [mipearson/webpack-rails#12]
`In CI, we manually run webpack to compile the assets to public and set config.webpack.dev_server.enabled to false.` - How do you set that config on your CI/which CI do you use?

**Comment by mipearson** [comment]
In our `test.rb` we have the following line:

``` ruby
  config.webpack.dev_server.enabled = !ENV['CI']
```

And we have `export CI=yes` at the start of our CI script.

We use the (absolutely amazing) buildkite.com

**Comment by mipearson** [comment]
We also have the following in our CI script to build the assets:

``` sh
echo "--- compile webpack assets"
mkdir -p public/webpack
TARGET=production ./node_modules/.bin/webpack --bail --config config/webpack.config.js
```

**Comment by mipearson** [comment]
(technically we could use the rake task to do this, but we don't want to wait for Ruby to start)

**Comment by Ch4s3** [comment]
Oh, cool. Incidentally I arrived at a near identical solution since posting. Maybe this should be in the readme?

**Comment by mipearson** [comment]
I think you are right! I will leave this issue open as a reminder.
