### ISSUE TITLE
react_on_rails for webpack?

### ISSUE THREAD

**Issue by justin808** [mipearson/webpack-rails#16]
Hi @mipearson, have you tried out https://github.com/shakacode/react_on_rails/? We've got support for integrating React + Webpack into Rails, including support for Redux.

If so, I'd be curious as to any potential shortfalls of react_on_rails compared to your approach.

Thanks!

**Comment by mibamur** [comment]
look at https://github.com/netguru/react_webpack_rails

**Comment by mipearson** [comment]
I haven't looked at `react_on_rails` in detail, but a skim through the readme shows that they've gone for a much more full-service solution than I have. Key differences:

  * webpack-rails doesn't depend on or use sprockets at all
  * webpack-rails insists that you understand the npm ecosystem and webpack

React server side rendering support is coming "soon" (it's working, I just need to clean up the docs).
