### ISSUE TITLE
css assets?

### ISSUE THREAD

**Issue by christianidylle** [mipearson/webpack-rails#20]
Doesn't seem the gem helper webpack_assets and manifest import css files properly. Any way to add this feature?

**Comment by mipearson** [comment]
I don't know - I haven't tried that. Give it a shot and submit a PR?

**Comment by mipearson** [comment]
Happy to try to fix this but I need an example to work from - at the very least a webpack.config.js

**Comment by zambrevishal** [comment]
@christianidylle  are you talking about https://github.com/knomedia/webpack_assets this gem?

**Comment by kyleknighted** [comment]
Whenever I use `<%= javascript_include_tag *webpack_asset_paths('application') %>` it outputs like

```html
<script src="//0.0.0.0:3808/webpack/application.js"></script>
<script src="//0.0.0.0:3808/webpack/application_style.css"></script>
```

My webpack config looks like 

```js
entry: {
    'application': [
      path.join(appAssetsDir, 'javascripts', 'application.js'),
      path.join(appAssetsDir, 'stylesheets', 'application.scss')
    ]
  }
```

It tries to load CSS like JS and gives errors. If I create a new `entry` and call it "app_style" and try to do `<%= stylesheet_link_tag *webpack_asset_paths('app_style') %>` then it outputs

```html
<link rel="stylesheet" media="screen" href="//0.0.0.0:3808/webpack/app_style.js" />
<link rel="stylesheet" media="screen" href="//0.0.0.0:3808/webpack/app_style_style.css" /
```

Which loads the CSS in properly now, but it's trying to load a non-existent JS as a stylesheet now.

Would be nice if there were a single method that you provide it a single entry point and if `${entry-point}_style` exists, then it will output the CSS, otherwise it just outputs the JS.

Let me know if I can help provide additional information.

**Comment by mipearson** [comment]
Ah, I see.

What if we change the method signature of `webpack_asset_paths`, so you can do:

``` erb
<%= javascript_include_tag *webpack_asset_paths('application', extension: 'js') %>
<%= stylesheet_link_tag *webpack_asset_paths('application', extension: 'css') %>
```

**Comment by kyleknighted** [comment]
Something like that would work great... if the extension defaulted to the obvious with the option to change it, that would be great.

**Comment by jum-s** [comment]
Hey kyle,
We are also having some difficulties to generate an `application.css` from `<%= javascript_include_tag *webpack_asset_paths('application') %>`. 
No idea how you end up with `application_style.css`. Is there a tricky line in the config file to generate specific names ? Do you use [ExtractTextPlugin](https://github.com/webpack/extract-text-webpack-plugin) ?
Would be glad to have a look at your config, here is [ours](https://gist.github.com/jum-s/d137bfe7e3f046c0dfa35a01bd4b6f37)
cheers

**Comment by kyleknighted** [comment]
@jum-s Probably not the best place for this entire discussion, but my webpack configuration is very large and is built out for Docker environments with multiple staging/production/development capabilities to render things differently as necessary, so my entire config would be beyond the scope of your concerns. 

In general, for CSS we are doing something along the lines of

```
entry: {
    'application': [
      path.join(appAssetsDir, 'javascripts', 'application.js'),
      path.join(appAssetsDir, 'stylesheets', 'application.css')
    ]
  },

  output: {
    path: path.join(__dirname, '..', 'app', 'assets'),
    publicPath: '/assets/',

    filename: production ? '[name]-[chunkhash].js' : '[name].js'
  },

  module: {
    loaders: [
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('css')
      }
    ]
  },

  plugins: [
    new ExtractTextPlugin(production ? '[name]-[chunkhash]_style.css' : '[name]_style.css')
  ]
```

Much more than that, I would recommend reaching out on StackOverflow for additional help and understanding of webpack configuration files.

**Comment by jum-s** [comment]
youre right for the discussion not at the right place, but thanks !

**Comment by kyleknighted** [comment]
@mipearson I tinkered a bit this morning and added a quick helper method to my applciation_helper.rb so that I could have it output both JS and CSS

```rb
module ApplicationHelper
  def webpack_assets(bundle)
    response = webpack_asset_paths(bundle)

    response.map do |res|
      f = res.split('.')

      if f.last == "js"
        javascript_include_tag(res)
      elsif f.last == "css"
        stylesheet_link_tag(res)
      end
    end.join("\n").html_safe
  end
end
```

and then in my layout erb

```erb
<%= webpack_assets('application') %>
```

**Comment by mipearson** [comment]
`extension:` added as an argument to gem release 0.9.7
