### ISSUE TITLE
package.json information should flex with rails application

### ISSUE THREAD

**Issue by MattWButler** [mipearson/webpack-rails#22]
This data is static, it seems like it should at least get the name from the rails application. 

{
  "name": "webpack-rails-example",
  "version": "0.0.1",
  "license": "MIT",
  "dependencies": {
    "stats-webpack-plugin": "^0.2.1",
    "webpack": "^1.9.11",
    "webpack-dev-server": "^1.9.0"
  }
}

**Comment by mipearson** [comment]
It's example code only, and I'd prefer to keep the code simple as the file is intended to be edited.

Happy to accept a PR if you get a clean solution though. Re-open if so.

**Comment by MattWButler** [comment]
Alright, thank you for your response.
