### ISSUE TITLE
explicitly define assets server protocol

### ISSUE THREAD

**Issue by twojustin** [mipearson/webpack-rails#36]
we just incorporated this into our development process.  but we noticed a small snag. we need to serve the assets out of https, while our rails server runs on http. This is because we have a web product (rails server) and a chrome extension product.  the chrome extension code must load from an https end point.

since the https setting is already exposed, but it's only used when looking for the inital manifest.json, i thought it would make sense to extend that to the assets themselves as well.

please consider #35

**Comment by mipearson** [comment]
Merged, thank you.
