### ISSUE TITLE
Accessing assets from the asset pipeline

### ISSUE THREAD

**Issue by willcosgrove** [mipearson/webpack-rails#37]
I've got some image paths that I need to reference in my webpack built javascript.  The images are part of the asset pipeline, living in `app/assets/images`, because they need to be accessible from the rails views also.

I can think of a few ways to get the paths to JS, but before I started trying things myself, I figured I would check and see if there was an already established way of doing something like this.

**Comment by mipearson** [comment]
Not officially, unfortunately - and I've been keeping webpack / sprockets as two separate systems deliberately (so that, perhaps, we can later stop using sprockets)
