### ISSUE TITLE
Heroku Build fails

### ISSUE THREAD

**Issue by Zinssmeister** [mipearson/webpack-rails#43]
Locally rake webpack:compile works like a charm but trying to deploy the app to heroku is a no go, but without much explanation. Looks like the manifest.json file isn't being properly created?

-----> Building dependencies
       Installing node modules (package.json)
       webpack-rails-example@0.0.1 /tmp/build_1c302d7f0ee64607177b83a9037152d4/Design-Inc-DI-app-7136c106d1427415463d0c2b3757798123617599
       ├─┬ babel-core@6.11.4
       │ ├─┬ babel-code-frame@6.11.0
       │ │ ├─┬ chalk@1.1.3
       │ │ │ ├── ansi-styles@2.2.1
       │ │ │ ├── escape-string-regexp@1.0.5
       │ │ │ ���── has-ansi@2.0.0
       │ │ │ └── supports-color@2.0.0
       │ │ ├── esutils@2.0.2
       │ │ └── js-tokens@2.0.0
       │ ├─┬ babel-generator@6.11.4
       │ │ └─┬ detect-indent@3.0.1
       │ │   ├── get-stdin@4.0.1
       │ │   ├── minimist@1.2.0
       │ │   └─┬ repeating@1.1.3
       │ │     └─┬ is-finite@1.0.1
       │ │       └── number-is-nan@1.0.0
       │ ├── babel-helpers@6.8.0
       │ ├── babel-messages@6.8.0
       │ ├─┬ babel-register@6.9.0
       │ │ ├── core-js@2.4.1
       │ │ ├─┬ home-or-tmp@1.0.0
       │ │ │ ├── os-tmpdir@1.0.1
       │ │ │ └── user-home@1.1.1
       │ │ └─┬ source-map-support@0.2.10
       │ │   └── source-map@0.1.32
       │ ├─┬ babel-runtime@6.9.2
       │ │ └── regenerator-runtime@0.9.5
       │ ├── babel-template@6.9.0
       │ ├─┬ babel-traverse@6.11.4
       │ │ ├── globals@8.18.0
       │ │ └── invariant@2.2.1
       │ ├─┬ babel-types@6.11.1
       │ │ └── to-fast-properties@1.0.2
       │ ├── babylon@6.8.4
       │ ├── convert-source-map@1.3.0
       │ ├─┬ debug@2.2.0
       │ │ └── ms@0.7.1
       │ ├── json5@0.4.0
       │ ├── lodash@4.13.1
       │ ├─┬ minimatch@3.0.2
       │ │ └─┬ brace-expansion@1.1.6
       │ │   ├── balanced-match@0.4.2
       │ │   └── concat-map@0.0.1
       │ ├── path-exists@1.0.0
       │ ├── path-is-absolute@1.0.0
       │ ├── private@0.1.6
       │ ├── shebang-regex@1.0.0
       │ ├── slash@1.0.0
       │ └── source-map@0.5.6
       ├─┬ babel-loader@6.2.4
       │ ├─┬ loader-utils@0.2.15
       │ │ ├── big.js@3.1.3
       │ │ ├── emojis-list@2.0.1
       │ │ └── json5@0.5.0
       │ ├─┬ mkdirp@0.5.1
       │ │ └── minimist@0.0.8
       │ └── object-assign@4.1.0
       ├─┬ babel-preset-es2015@6.9.0
       │ ├── babel-plugin-check-es2015-constants@6.8.0
       │ ├── babel-plugin-transform-es2015-arrow-functions@6.8.0
       │ ├── babel-plugin-transform-es2015-block-scoped-functions@6.8.0
       │ ├── babel-plugin-transform-es2015-block-scoping@6.10.1
       │ ├─┬ babel-plugin-transform-es2015-classes@6.9.0
       │ │ ├── babel-helper-define-map@6.9.0
       │ │ ├── babel-helper-function-name@6.8.0
       │ │ ├── babel-helper-optimise-call-expression@6.8.0
       │ │ └── babel-helper-replace-supers@6.8.0
       │ ├── babel-plugin-transform-es2015-computed-properties@6.8.0
       │ ├── babel-plugin-transform-es2015-destructuring@6.9.0
       │ ├── babel-plugin-transform-es2015-duplicate-keys@6.8.0
       │ ├── babel-plugin-transform-es2015-for-of@6.8.0
       │ ├── babel-plugin-transform-es2015-function-name@6.9.0
       │ ├── babel-plugin-transform-es2015-literals@6.8.0
       │ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.10.3
       │ │ └── babel-plugin-transform-strict-mode@6.11.3
       │ ├── babel-plugin-transform-es2015-object-super@6.8.0
       │ ├─┬ babel-plugin-transform-es2015-parameters@6.11.4
       │ │ ├─┬ babel-helper-call-delegate@6.8.0
       │ │ │ └── babel-helper-hoist-variables@6.8.0
       │ │ └── babel-helper-get-function-arity@6.8.0
       │ ├── babel-plugin-transform-es2015-shorthand-properties@6.8.0
       │ ├── babel-plugin-transform-es2015-spread@6.8.0
       │ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.8.0
       │ │ └── babel-helper-regex@6.9.0
       │ ├── babel-plugin-transform-es2015-template-literals@6.8.0
       │ ├── babel-plugin-transform-es2015-typeof-symbol@6.8.0
       │ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.11.0
       │ │ └─┬ regexpu-core@2.0.0
       │ │   ├── regenerate@1.3.1
       │ │   ├── regjsgen@0.2.0
       │ │   └─┬ regjsparser@0.1.5
       │ │     └── jsesc@0.5.0
       │ └─┬ babel-plugin-transform-regenerator@6.11.4
       │   └── babel-plugin-syntax-async-functions@6.8.0
       ├─┬ babel-preset-react@6.11.1
       │ ├── babel-plugin-syntax-flow@6.8.0
       │ ├── babel-plugin-syntax-jsx@6.8.0
       │ ├── babel-plugin-transform-flow-strip-types@6.8.0
       │ ├── babel-plugin-transform-react-display-name@6.8.0
       │ ├─┬ babel-plugin-transform-react-jsx@6.8.0
       │ │ └── babel-helper-builder-react-jsx@6.9.0
       │ ├── babel-plugin-transform-react-jsx-self@6.11.0
       │ └── babel-plugin-transform-react-jsx-source@6.9.0
       ├─┬ react@15.2.1
       │ ├─┬ fbjs@0.8.3
       │ │ ├── core-js@1.2.7
       │ │ ├── immutable@3.8.1
       │ │ ├─┬ isomorphic-fetch@2.2.1
       │ │ │ ├─┬ node-fetch@1.5.3
       │ │ │ │ ├─┬ encoding@0.1.12
       │ │ │ │ │ └── iconv-lite@0.4.13
       │ │ │ │ └── is-stream@1.1.0
       │ │ │ └── whatwg-fetch@1.0.0
       │ │ ├─┬ promise@7.1.1
       │ │ │ └── asap@2.0.4
       │ │ └── ua-parser-js@0.7.10
       │ └─┬ loose-envify@1.2.0
       │   └── js-tokens@1.0.3
       ├── react-addons-css-transition-group@15.2.1
       ├── react-dom@15.2.1
       ├── stats-webpack-plugin@0.2.2
       ├─┬ webpack@1.13.1
       │ ├── acorn@3.2.0
       │ ├── async@1.5.2
       │ ├── clone@1.0.2
       │ ├─┬ enhanced-resolve@0.9.1
       │ │ ├── graceful-fs@4.1.4
       │ │ └── memory-fs@0.2.0
       │ ├── interpret@0.6.6
       │ ├─┬ memory-fs@0.3.0
       │ │ ├─┬ errno@0.1.4
       │ │ │ └── prr@0.0.0
       │ │ └─┬ readable-stream@2.1.4
       │ │   ├── buffer-shims@1.0.0
       │ │   ├── core-util-is@1.0.2
       │ │   ├── isarray@1.0.0
       │ │   ├── process-nextick-args@1.0.7
       │ │   └── util-deprecate@1.0.2
       │ ├─┬ node-libs-browser@0.5.3
       │ │ ├── assert@1.4.1
       │ │ ├─┬ browserify-zlib@0.1.4
       │ │ │ └── pako@0.2.9
       │ │ ├─┬ buffer@3.6.0
       │ │ │ ├── base64-js@0.0.8
       │ │ │ └── ieee754@1.1.6
       │ │ ├─┬ console-browserify@1.1.0
       │ │ │ └── date-now@0.1.4
       │ │ ├── constants-browserify@0.0.1
       │ │ ├─┬ crypto-browserify@3.2.8
       │ │ │ ├── pbkdf2-compat@2.0.1
       │ │ │ ├── ripemd160@0.2.0
       │ │ │ └── sha.js@2.2.6
       │ │ ├── domain-browser@1.1.7
       │ │ ├── events@1.1.1
       │ │ ├─┬ http-browserify@1.7.0
       │ │ │ └── Base64@0.2.1
       │ │ ├── https-browserify@0.0.0
       │ │ ├── os-browserify@0.1.2
       │ │ ├── path-browserify@0.0.0
       │ │ ├── process@0.11.5
       │ │ ├── punycode@1.4.1
       │ │ ├── querystring-es3@0.2.1
       │ │ ├─┬ readable-stream@1.1.14
       │ │ │ └── isarray@0.0.1
       │ │ ├─┬ stream-browserify@1.0.0
       │ │ │ └─┬ readable-stream@1.1.14
       │ │ │   └── isarray@0.0.1
       │ │ ├── string_decoder@0.10.31
       │ │ ├── timers-browserify@1.4.2
       │ │ ├── tty-browserify@0.0.0
       │ │ ├─┬ url@0.10.3
       │ │ │ ├── punycode@1.3.2
       │ │ │ └── querystring@0.2.0
       │ │ ├── util@0.10.3
       │ │ └─┬ vm-browserify@0.0.4
       │ │   └── indexof@0.0.1
       │ ├─┬ optimist@0.6.1
       │ │ ├── minimist@0.0.10
       │ │ └── wordwrap@0.0.3
       │ ├─┬ supports-color@3.1.2
       │ │ └── has-flag@1.0.0
       │ ├── tapable@0.1.10
       │ ├─┬ uglify-js@2.6.4
       │ │ ├── async@0.2.10
       │ │ ├── uglify-to-browserify@1.0.2
       │ │ └─┬ yargs@3.10.0
       │ │   ├── camelcase@1.2.1
       │ │   ├─┬ cliui@2.1.0
       │ │   │ ├─┬ center-align@0.1.3
       │ │   │ │ ├─┬ align-text@0.1.4
       │ │   │ │ │ ├── longest@1.0.1
       │ │   │ │ │ └── repeat-string@1.5.4
       │ │   │ │ └── lazy-cache@1.0.4
       │ │   │ ├── right-align@0.1.3
       │ │   │ └── wordwrap@0.0.2
       │ │   ├── decamelize@1.2.0
       │ │   └── window-size@0.1.0
       │ ├─┬ watchpack@0.2.9
       │ │ ├── async@0.9.2
       │ │ └─┬ chokidar@1.6.0
       │ │   ├─┬ anymatch@1.3.0
       │ │   │ ├── arrify@1.0.1
       │ │   │ └─┬ micromatch@2.3.11
       │ │   │   ├─┬ arr-diff@2.0.0
       │ │   │   │ └── arr-flatten@1.0.1
       │ │   │   ├── array-unique@0.2.1
       │ │   │   ├─┬ braces@1.8.5
       │ │   │   │ ├─┬ expand-range@1.8.2
       │ │   │   │ │ └─┬ fill-range@2.2.3
       │ │   │   │ │   ├── is-number@2.1.0
       │ │   │   │ │   ├── isobject@2.1.0
       │ │   │   │ │   └── randomatic@1.1.5
       │ │   │   │ ├── preserve@0.2.0
       │ │   │   │ └── repeat-element@1.1.2
       │ │   │   ├─┬ expand-brackets@0.1.5
       │ │   │   │ └── is-posix-bracket@0.1.1
       │ │   │   ├── extglob@0.3.2
       │ │   │   ├── filename-regex@2.0.0
       │ │   │   ├─┬ kind-of@3.0.3
       │ │   │   │ └── is-buffer@1.1.3
       │ │   │   ├── normalize-path@2.0.1
       │ │   │   ├─┬ object.omit@2.0.0
       │ │   │   │ ├─┬ for-own@0.1.4
       │ │   │   │ │ └── for-in@0.1.5
       │ │   │   │ └── is-extendable@0.1.1
       │ │   │   ├─┬ parse-glob@3.0.4
       │ │   │   │ ├── glob-base@0.3.0
       │ │   │   │ └── is-dotfile@1.0.2
       │ │   │   └─┬ regex-cache@0.4.3
       │ │   │     ├── is-equal-shallow@0.1.3
       │ │   │     └── is-primitive@2.0.0
       │ │   ├── async-each@1.0.0
       │ │   ├── glob-parent@2.0.0
       │ │   ├─┬ is-binary-path@1.0.1
       │ │   │ └── binary-extensions@1.5.0
       │ │   ├─┬ is-glob@2.0.1
       │ │   │ └── is-extglob@1.0.0
       │ │   └─┬ readdirp@2.1.0
       │ │     └── set-immediate-shim@1.0.1
       │ └─┬ webpack-core@0.6.8
       │   ├── source-list-map@0.1.6
       │   └─┬ source-map@0.4.4
       │     └── amdefine@1.0.0
       └─┬ webpack-dev-server@1.14.1
       ├─┬ compression@1.6.2
       │ ├─┬ accepts@1.3.3
       │ │ └── negotiator@0.6.1
       │ ├── bytes@2.3.0
       │ ├─┬ compressible@2.0.8
       │ │ └── mime-db@1.23.0
       │ ├── on-headers@1.0.1
       │ └── vary@1.1.0
       ├── connect-history-api-fallback@1.1.0
       ├─┬ express@4.14.0
       │ ├── array-flatten@1.1.1
       │ ├── content-disposition@0.5.1
       │ ├── content-type@1.0.2
       │ ├── cookie@0.3.1
       │ ├── cookie-signature@1.0.6
       │ ├── depd@1.1.0
       │ ├── encodeurl@1.0.1
       │ ├── escape-html@1.0.3
       │ ├── etag@1.7.0
       │ ├─┬ finalhandler@0.5.0
       │ │ ├── statuses@1.3.0
       │ │ └── unpipe@1.0.0
       │ ├── fresh@0.3.0
       │ ├── merge-descriptors@1.0.1
       │ ├── methods@1.1.2
       │ ├─┬ on-finished@2.3.0
       │ │ └── ee-first@1.1.1
       │ ├── parseurl@1.3.1
       │ ├── path-to-regexp@0.1.7
       │ ├─┬ proxy-addr@1.1.2
       │ │ ├── forwarded@0.1.0
       │ │ └── ipaddr.js@1.1.1
       │ ├── qs@6.2.0
       │ ├── range-parser@1.2.0
       │ ├─┬ send@0.14.1
       │ │ └── destroy@1.0.4
       │ ├── serve-static@1.11.1
       │ ├─┬ type-is@1.6.13
       │ │ └── media-typer@0.3.0
       │ └── utils-merge@1.0.0
       ├─┬ http-proxy@1.14.0
       │ ├── eventemitter3@1.2.0
       │ └── requires-port@1.0.0
       ├─┬ serve-index@1.8.0
       │ ├── batch@0.5.3
       │ ├─┬ http-errors@1.5.0
       │ │ └── setprototypeof@1.0.1
       │ └── mime-types@2.1.11
       ├─┬ sockjs@0.3.17
       │ ├─┬ faye-websocket@0.10.0
       │ │ └─┬ websocket-driver@0.6.5
       │ │   └── websocket-extensions@0.1.1
       │ └── uuid@2.0.2
       ├─┬ sockjs-client@1.1.1
       │ ├─┬ eventsource@0.1.6
       │ │ └─┬ original@1.0.0
       │ │   └── url-parse@1.0.5
       │ ├── faye-websocket@0.11.0
       │ ├── inherits@2.0.1
       │ ├── json3@3.3.2
       │ └─┬ url-parse@1.1.1
       │   └── querystringify@0.0.3
       ├── stream-cache@0.0.2
       ├─┬ strip-ansi@3.0.1
       │ └── ansi-regex@2.0.0
       ├── supports-color@3.1.2
       └─┬ webpack-dev-middleware@1.6.1
       └── mime@1.3.4
       
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
       ├── babel-core@6.11.4
       ├── babel-loader@6.2.4
       ├── babel-preset-es2015@6.9.0
       ├── babel-preset-react@6.11.1
       ├── react@15.2.1
       ├── react-addons-css-transition-group@15.2.1
       ├── react-dom@15.2.1
       ├── stats-webpack-plugin@0.2.2
       ├── webpack@1.13.1
       └── webpack-dev-server@1.14.1
       
-----> webpack-rails app detected
-----> bundle exec rake webpack:compile
rake aborted!
Hash: 56f5734cd4cb126789c6
Version: webpack 1.13.1
Time: 3988ms
                        Asset     Size  Chunks             Chunk Names
index-d11041cf5e228483e04a.js   152 kB       0  [emitted]  index
                manifest.json  0 bytes          [emitted]

**Comment by skorth** [comment]
Same problem here on my Capistrano deployment. Current master (including this fix) works for me. Please release 👍 .

**Comment by mipearson** [comment]
v.0.9.9 released :)

**Comment by skorth** [comment]
thx 👍
