### ISSUE TITLE
Would like to change publicPath 

### ISSUE THREAD

**Issue by Zinssmeister** [mipearson/webpack-rails#45]
Out of the box the publicPath is **public/webpack/**, I tried changing it to **public/js**, which compiles fine into that location but it does not seem to find it there.

`ActionView::Template::Error (Could not load compiled manifest from /app/public/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /app/public/webpack/manifest.json)):`

Is there anything I'm missing? Is it possible to change the output location?

**Comment by juanca** [comment]
Yeah, the rails configuration should also point to the correct path, (in my case, we use `public/compiled`) 

e.g.

```
Rails.configuration.webpack.output_dir = 'public/compiled'
Rails.configuration.webpack.public_path = 'compiled'
```
