### ISSUE TITLE
Could not find generator webpack_rails:install.

### ISSUE THREAD

**Issue by danawoodman** [mipearson/webpack-rails#5]
Using Rails 3.2.18 and Ruby 2.0 I'm getting the following when running `bundle exec rails generate webpack_rails:install` (after successful `bundle install` of `webpack-rails`):

```
Could not find generator webpack_rails:install.
```

Any idea what could cause this?

**Comment by mipearson** [comment]
Reproduced here. I can see `webpack_rails:install` in the generators list but attempting to invoke it gives an error.

**Comment by mipearson** [comment]
Fixed in 0.9.4

**Comment by mipearson** [comment]
btw, thanks for the report! I tested it, renamed the generator, and assumed it was "working" because I could see it in the generators list.
