### ISSUE TITLE
not working on production

### ISSUE THREAD

**Issue by andreipot** [mipearson/webpack-rails#54]
Hello @mipearson  thanks for your great work! I've used this gem and webpack is working great with rails on local.

However I deployed app to AWS opswork and did rake webpack:compile, I get this error.
#2432 ActionView::Template::Error: Could not load manifest from webpack-dev-server at http://localhost:3808/webpack/manifest.json - is it running, and is stats-webpack-plugin loaded? (original error Connection refused - connect(2) for "localhost" port 3808) 

We're not accessing localhost:3808 on production right? Do you have any idea why I got this error?

Thanks.

**Comment by mipearson** [comment]
Hi,

For some reason `config.webpack.dev_server.enabled` must still be set to true.

Can you double-check that your rails app is running in production mode in AWS opswork?

**Comment by andreipot** [comment]
I'm sure rails app is running in production mode.

I just set NODE env as production but still getting same error.

And do I have to set config.webpack.dev_server.enabled  = true in env/production.rb?

**Comment by mipearson** [comment]
Nope - it needs to be false. If it's false, it'll rely on pre-compiled assets instead.

I would recommend confirming the environment that your production app is running in by putting this just above your javascript require line in your layout:

```erb
<% raise "Not production" unless Rails.env.production? %>
<% raise Rails.application.configuration.configuration.webpack.inspect %>
```

Then we can also see the configuration.

**Comment by andreipot** [comment]
#2460 ActionView::Template::Error: Could not load compiled manifest from /srv/www/bookthatapp/releases/20160907084459/public/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /srv/www/bookthata

NOw I got this error. seems like we'r relying on pre-compiled asset. The problem is I did run rake webpack:compile both via recipe and manually in server.

My concern is it's looking for compile file in /releases folder though app is deployed under /current

**Comment by mipearson** [comment]
`current` is usually a symlink to a particular release, at least in the capistrano pattern. Unfortunately, I can't help you much further than here as I'm not familiar enough with AWS opswork or capistrano to understand where this might have fallen over.

**Comment by andreipot** [comment]
OK, thanks for your help, I will ask your help only related with webpack :)

**Comment by mipearson** [comment]
Best of luck! Let me know if you come up with a solution. Note that it's most likely referencing the `releases` directory as I (think) it calls `File.expand_path`, which resolves symlinks.

**Comment by andreipot** [comment]
RuntimeError: Not production I got this. I think it's because I'm deploying to staging environment. How can we use precomipled asset on staging?

**Comment by mipearson** [comment]
Set config.webpack.dev_server.enabled = false in your staging.rb file

**Comment by andreipot** [comment]
already did.

**Comment by andreipot** [comment]
will check more and share my update with you .thanks.

**Comment by andreipot** [comment]
ok, I fixed. it was related with opswork settings. thanks @mipearson !

**Comment by mubarakadeimam** [comment]
@andreipot, kindly explain how you fixed this error. I am currently having same issue. Thanks in advance.
