### ISSUE TITLE
Suggest handling live-reload in development by default

### ISSUE THREAD

**Issue by chrisnicola** [mipearson/webpack-rails#7]
I had to add `<script src="http://localhost:3808/webpack-dev-server.js"></script>` to my layout template in order to get livereload working. I'd suggest enabling this by default or via configuration so that it "just works".

**Comment by mipearson** [comment]
Interesting (not on laptop, so email will have to do).

We've only used react-hot-reload here.

I'd prefer to add a hint to the documentation rather than make this
standard behaviour.

On Sat, Nov 21, 2015 at 9:28 AM, Chris Nicola <notifications@github.com>
wrote:

> I had to add <script src="http://localhost:3808/webpack-dev-server.js
> "></script> to my layout template in order to get livereload working. I'd
> suggest enabling this by default or via configuration so that it "just
> works".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mipearson/webpack-rails/issues/7>.
>



-- 
Michael Pearson

**Comment by chrisnicola** [comment]
That sounds good to me. I'll likely put together some sort of config though so if you are interested I'd be happy to submit a pull request.

**Comment by chrisnicola** [comment]
BTW, thanks so much for this. Saved me so much time and made it really easy to get started. Switching to Webpack has been a huge improvement over Sprockets.

**Comment by chrisnicola** [comment]
FYI, I've found that starting the webpack dev server with --inline also fixes this. It loads the webpack server inline with the other scripts automatically. This is what we do now.
