### ISSUE TITLE
Code Splitting 

### ISSUE THREAD

**Issue by allenwq** [mipearson/webpack-rails#82]
Does this project work with webpack code splitting?  https://webpack.github.io/docs/code-splitting.html

From the scourse code, it seems not. Because `:assetsByChunkName` doesn't differentiate static files and dynamically required files.

Can someone confirm ?

**Comment by juanca** [comment]
We split our common code into its own file (via the common chunks plugin). And require the file whenever it is a dependency.

It would be great to do this automatically but it doesn't seem to work outta the box. 


e.g.

```
var webpack = require("webpack");

module.exports = {
  entry: {
    app: "./app.js",
    vendor: ["jquery", "underscore", ...],
  },
  output: {
    filename: "bundle.js"
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin(/* chunkName= */"vendor", /* filename= */"vendor.bundle.js")
  ]
};
```

```
<%= javascript_include_tag *webpack_asset_paths('vendor', extension: 'js') %>
<%= javascript_include_tag *webpack_asset_paths('app', extension: 'js') %>
```

**Comment by mipearson** [comment]
We use the commons plugin with this plugin at Marketplacer as described in @juanca's comment.

The current behaviour will not be changing: you will need to explicitly include the `vendor` asset.

**Comment by allenwq** [comment]
👍 Explicitness is good, that's what I want.

I don't want all generated modules be included by default.
